name: DTC CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup SBT
        uses: olafurpg/setup-scala@v13
        with:
          java-version: '21'
          
      - name: Run tests
        run: sbt clean validate

  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup SBT
        uses: olafurpg/setup-scala@v13
        with:
          java-version: '21'
          
      - uses: scalacenter/sbt-dependency-submission@v2
