name: DTC CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt clean validate
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91

#      - name: Coverage Report
#        run: sbt coverageReport
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          fail_ci_if_error: true
